name: Model Calibration on Push to Main
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  calibrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate Timestamp for Calibration
      run: echo "timestamp=$(date '+%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create directories
      run: |
        mkdir -p models/calibrated

    - name: Find Latest Model
      id: latest_model
      run: |
        latest=$(ls -t models/model_*_dt_model.joblib | head -n 1)
        echo "latest_model=$latest" >> $GITHUB_ENV
        echo "Latest model found: $latest"

    - name: Calibrate Model
      run: |
        python ./src/calibrate_model.py \
          --input_model "$latest_model" \
          --output_model "models/calibrated/calibrated_model_${timestamp}.joblib"

    - name: Commit and Push Calibrated Model
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add models/calibrated/calibrated_model_${timestamp}.joblib
        git commit -m "Add calibrated model version $timestamp"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
